# Generated by Django 4.0.4 on 2022-05-11 07:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersInfo',
            fields=[
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_name', models.CharField(max_length=20, null=True)),
                ('user_age', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('user_level', models.CharField(choices=[('헬생아', '헬생아'), ('헬린이', '헬린이'), ('헬스인', '헬스인'), ('헬창', '헬창')], default='헬생아', max_length=10)),
                ('user_type', models.CharField(max_length=10, null=True)),
                ('user_purpose', models.CharField(max_length=10, null=True)),
                ('workout_time', models.PositiveSmallIntegerField(null=True)),
                ('workout_per_week', models.PositiveSmallIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_info',
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=100, unique=True)),
                ('user_authentication', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('user_info_input', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['created_at'],
            },
        ),
    ]
