# Generated by Django 4.0.4 on 2022-05-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountlist',
            table='AccountList',
        ),
        migrations.AlterModelTable(
            name='usersinfo',
            table='UsersInfo',
        ),
    ]
