# Generated by Django 4.0.4 on 2022-05-11 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_accountlist_id_alter_accountlist_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinfo',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.accountlist'),
        ),
    ]
