# Generated by Django 4.0.4 on 2022-05-25 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('image', models.FileField(null=True, upload_to='contentImage/')),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('UID', models.ForeignKey(db_column='uid_pr', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='uid_profiles', serialize=False, to='accounts.accountlist')),
                ('name', models.CharField(max_length=15, null=True)),
                ('subTitle', models.CharField(max_length=100, null=True)),
                ('subscribeNum', models.SmallIntegerField(default=0)),
                ('profileImg', models.TextField(null=True)),
                ('backgroundImg', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profiles',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Portfolios',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('portfolioWriterProfile', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('contentImage', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('likeN', models.IntegerField(default=0)),
                ('commentN', models.IntegerField(default=0)),
                ('postN', models.AutoField(primary_key=True, serialize=False)),
                ('portfolioWriter', models.ForeignKey(db_column='uid_por', on_delete=django.db.models.deletion.CASCADE, related_name='uid_portfolios', to='accounts.accountlist')),
            ],
            options={
                'db_table': 'portfolios',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioComments',
            fields=[
                ('commentN', models.AutoField(primary_key=True, serialize=False)),
                ('commentWriterProfile', models.TextField()),
                ('commentDate', models.DateTimeField(auto_now_add=True)),
                ('comContent', models.CharField(max_length=150)),
                ('commentWriter', models.ForeignKey(db_column='uid_cm', on_delete=django.db.models.deletion.CASCADE, related_name='uid_comments', to='accounts.accountlist')),
                ('postN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.portfolios')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['commentDate'],
            },
        ),
    ]
