# Generated by Django 4.0.4 on 2022-05-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('profiles', '0002_alter_profiles_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='portfolioWriter',
            field=models.ForeignKey(db_column='portfolioWriter', on_delete=django.db.models.deletion.CASCADE, to='accounts.accountlist'),
        ),
    ]
