# Generated by Django 4.0.4 on 2022-05-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_portfolios_portfoliowriterprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='contentImage',
            field=models.FileField(upload_to='contentImage/'),
        ),
    ]
