# Generated by Django 4.0.4 on 2022-05-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='contentImage',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
