# Generated by Django 4.0.4 on 2022-05-25 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('profiles', '0007_alter_portfolios_contentimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='id',
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='contentImage',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='UID',
            field=models.ForeignKey(db_column='uid_pr', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='uid_profiles', serialize=False, to='accounts.accountlist'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='backgroundImg',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='profileImg',
            field=models.TextField(null=True),
        ),
    ]
