# Generated by Django 4.0.4 on 2022-05-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_profiles_id_alter_portfolios_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='subTitle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
