# Generated by Django 3.2.12 on 2022-03-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_UID', models.CharField(default='', max_length=100)),
                ('user_name', models.CharField(max_length=10)),
                ('user_age', models.CharField(max_length=100)),
                ('user_level', models.CharField(max_length=40)),
                ('user_type', models.CharField(max_length=40)),
                ('user_purpose', models.CharField(max_length=40)),
                ('user_time', models.CharField(max_length=20)),
                ('user_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('user_UID',),
            },
        ),
    ]
