# Generated by Django 3.2.12 on 2022-03-11 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='UserInfo',
        ),
    ]
