# Generated by Django 4.0.4 on 2022-05-16 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanList',
            fields=[
                ('planName', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('likeNum', models.PositiveSmallIntegerField(default=0)),
                ('downloadNum', models.PositiveSmallIntegerField(default=0)),
                ('commentNum', models.PositiveSmallIntegerField(default=0)),
                ('hashTagChest', models.CharField(max_length=10, null=True)),
                ('hashTagBack', models.CharField(max_length=10, null=True)),
                ('hashTagLeg', models.CharField(max_length=10, null=True)),
                ('hashTagShoulder', models.CharField(max_length=10, null=True)),
                ('hashTagArm', models.CharField(max_length=10, null=True)),
                ('hashTagAir', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('UID', models.ForeignKey(db_column='UID', on_delete=django.db.models.deletion.CASCADE, to='accounts.accountlist')),
            ],
            options={
                'db_table': 'PlanList',
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutList',
            fields=[
                ('workoutID', models.AutoField(primary_key=True, serialize=False)),
                ('dayCount', models.SmallIntegerField(default=1)),
                ('workoutName', models.CharField(max_length=20)),
                ('setNum', models.SmallIntegerField(blank=True, null=True)),
                ('isComplete', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('UID', models.ForeignKey(db_column='UID', on_delete=django.db.models.deletion.CASCADE, to='accounts.accountlist')),
                ('planName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.planlist')),
            ],
            options={
                'db_table': 'WorkoutList',
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SetList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setCount', models.PositiveSmallIntegerField()),
                ('count', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('UID', models.ForeignKey(db_column='UID', on_delete=django.db.models.deletion.CASCADE, to='accounts.accountlist')),
                ('planName', models.ForeignKey(db_column='planName', on_delete=django.db.models.deletion.CASCADE, to='workout.planlist')),
                ('workoutName', models.ForeignKey(db_column='workoutName', on_delete=django.db.models.deletion.CASCADE, to='workout.workoutlist')),
            ],
            options={
                'db_table': 'SetList',
            },
        ),
    ]
