# Generated by Django 4.0.4 on 2022-05-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planlist',
            name='UID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutlist',
            name='UID',
            field=models.CharField(max_length=20),
        ),
    ]
