# Generated by Django 4.0.4 on 2022-05-16 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlist',
            name='planName',
            field=models.ForeignKey(db_column='planName', on_delete=django.db.models.deletion.CASCADE, to='workout.planlist'),
        ),
    ]
