# Generated by Django 4.0.4 on 2022-05-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_workoutlist_planname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlist',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='setlist',
            name='setCount',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='setlist',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
