# Generated by Django 4.0.4 on 2022-05-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_setlist_count_alter_setlist_setcount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlist',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setlist',
            name='setCount',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setlist',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
