# Generated by Django 4.0.4 on 2022-05-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_alter_setlist_count_alter_setlist_setcount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlist',
            name='workoutName',
            field=models.CharField(max_length=20),
        ),
    ]
