# Generated by Django 4.0.4 on 2022-05-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_alter_setlist_workoutname'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlist',
            name='planDay',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
