# Generated by Django 4.0.4 on 2022-05-21 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('workout', '0006_planlist_planday'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlist',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workoutlist',
            name='planName',
            field=models.ForeignKey(db_column='planName', null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.planlist'),
        ),
        migrations.CreateModel(
            name='LikeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_user', models.ForeignKey(db_column='like_user', on_delete=django.db.models.deletion.CASCADE, to='accounts.accountlist')),
                ('planName', models.ForeignKey(db_column='plan', on_delete=django.db.models.deletion.CASCADE, to='workout.planlist')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planName', models.ForeignKey(db_column='planName', on_delete=django.db.models.deletion.CASCADE, to='workout.planlist')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('UID', models.ForeignKey(db_column='UID', on_delete=django.db.models.deletion.CASCADE, to='accounts.accountlist')),
                ('planName', models.ForeignKey(db_column='planName', null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.planlist')),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
    ]
