# Generated by Django 4.0.4 on 2022-05-21 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('workout', '0007_planlist_user_alter_workoutlist_planname_likelist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlist',
            name='download_user',
            field=models.ForeignKey(db_column='download_user', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountlist'),
        ),
        migrations.AlterField(
            model_name='downloadlist',
            name='planName',
            field=models.ForeignKey(db_column='plan', on_delete=django.db.models.deletion.CASCADE, to='workout.planlist'),
        ),
    ]
