# Generated by Django 4.0.4 on 2022-05-23 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('workout', '0009_alter_downloadlist_table_alter_likelist_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.ForeignKey(db_column='name', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.usersinfo'),
        ),
    ]
