# Generated by Django 4.0.4 on 2022-05-25 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0012_rename_comment_plancomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlist',
            name='planName',
            field=models.ForeignKey(db_column='planName', on_delete=django.db.models.deletion.CASCADE, to='workout.planlist'),
        ),
        migrations.AlterField(
            model_name='likelist',
            name='planName',
            field=models.ForeignKey(db_column='planName', on_delete=django.db.models.deletion.CASCADE, to='workout.planlist'),
        ),
    ]
