# Generated by Django 4.0.4 on 2022-06-01 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0013_alter_downloadlist_planname_alter_likelist_planname'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlist',
            name='workoutID',
            field=models.ForeignKey(db_column='workoutUID', null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.workoutlist'),
        ),
    ]
